version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=vino
      - DB_PASSWORD=vino
      - DB_NAME=Vino
    command: python main.py
    network_mode: host
